FROM alpine:latest

WORKDIR /root

RUN apk update
RUN apk upgrade
RUN apk add expect
RUN apk add openssl
RUN apk add nodejs npm

COPY ./backend ./
COPY ./frontend ./code

RUN npm i
RUN cd code && npm i 
RUN cd code && npm run build
RUN cp -r ./code/build ./build
RUN cd scripts && chmod +x installCa.sh
RUN cd scripts && /bin/sh installCa.sh "https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.6/EasyRSA-3.1.6.tgz"

EXPOSE 8008

ENTRYPOINT [ "node", "app.js" ]