FROM alpine:latest

WORKDIR /app

RUN apk update
RUN apk upgrade
RUN apk add expect
RUN apk add openssl
RUN apk add nodejs npm

COPY ./backend ./
COPY ./frontend ./code

RUN npm i
RUN cd code && npm i 
RUN cd code && npm run build
RUN cp -r ./code/build ./build
RUN cp ./scripts/installCa.sh installCa.sh
RUN chmod +x /app/installCa.sh 
RUN installCa.sh https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.2/EasyRSA-3.1.2.tgz

EXPOSE 8008

ENTRYPOINT [ "node", "app.js" ]